site_name: Документация для работы с платформой

nav:
  - Ученик:
    - ig/index.md
    - Работа с курсами:
      - ig/projects.md
      - ig/testing.md
    - ig/olympiads.md
  - Учитель:
    - ag/index.md
    - ag/teacher_courses.md
    - ag/teacher_project.md
  - Координатор:
    - kg/index.md

theme:
  name: material
  language: ru
  logo: assets/logo.png
  favicon: assets/logo_fav.png
  features:
    - navigation.instant # ускорение загрузки (SPA) ссылок
    - navigation.instant.prefetch # ускорение предварительной выборки
    - navigation.instant.progress # индикатор прогресса
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # перенос названий документов в горизонтальное меню
    - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    - navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх
    # - navigation.sections # разделы навигации для мобильных
    # - navigation.expand # Ррасширенная навигация
    - navigation.path # путь навигации
    - navigation.prune # видимые элементы навигации
    - toc.follow # отслеживание якоря для оглавления
    # - toc.integrate # интеграция навигации для оглавления
  palette: 
    - scheme: default
      accent: orange
      toggle:
        icon: material/weather-night
        name: Ночь
    - scheme: slate
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: День

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: 
        - en
        - ru
  - mkpdfs:
      company: ООО «Цифровое образование»
      author: Господарик
